# Generated by Django 4.1 on 2024-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Tell_About_Project', models.CharField(max_length=500)),
            ],
        ),
    ]
