# Generated by Django 4.1 on 2024-03-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSubmit',
            new_name='Contact',
        ),
    ]
