# Generated by Django 4.1 on 2024-03-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tell_about_project_contact_about_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='About_Project',
            new_name='Comments',
        ),
    ]
