# Generated by Django 3.2.23 on 2024-03-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_about_project_contact_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='title', max_length=225)),
                ('Image1', models.ImageField(upload_to='uploads/')),
                ('CropYear', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('Nic', models.CharField(max_length=100)),
                ('Sug', models.CharField(max_length=100)),
                ('Packing', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-Create_at'],
            },
        ),
    ]
