# Generated by Django 3.2.23 on 2024-04-01 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='title', max_length=225)),
                ('Image1', models.ImageField(upload_to='uploads/')),
                ('CropYear', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('Nic', models.CharField(max_length=100)),
                ('Sug', models.CharField(max_length=100)),
                ('Packing', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-Create_at'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
