# Generated by Django 3.2.23 on 2024-04-01 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240401_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='uploads/')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'ImageCategory',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Productitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='title', max_length=225)),
                ('CropYear', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('Nic', models.CharField(max_length=100)),
                ('Sug', models.CharField(max_length=100)),
                ('Packing', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('ImageCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.imagecategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Productitem',
        ),
    ]
