# Generated by Django 3.2.23 on 2024-04-01 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240401_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='category_images/')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Image Category',
                'verbose_name_plural': 'Image Categories',
            },
        ),
        migrations.AlterField(
            model_name='productitems',
            name='ImageCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.imagecategorys'),
        ),
        migrations.DeleteModel(
            name='ImageCategory',
        ),
    ]
