# Generated by Django 4.1 on 2024-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240402_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='title', max_length=225)),
                ('Planting', models.CharField(max_length=100)),
                ('Marketing', models.CharField(max_length=100)),
                ('Colour', models.CharField(max_length=100)),
                ('Leaf_Size', models.CharField(max_length=100)),
                ('Volume', models.CharField(max_length=100)),
                ('Filling_Value', models.CharField(max_length=100)),
                ('Nicotine', models.CharField(max_length=100)),
                ('Reducing_Sugars', models.CharField(max_length=100)),
                ('Chloride', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Productitem',
        # ),
    ]
