# Generated by Django 4.1 on 2024-04-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productitems_delete_productitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='Volume',
            new_name='Volumes',
        ),
    ]
