# Generated by Django 4.1 on 2024-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_volume_productitem_volumes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='Volumes',
            new_name='Volume',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='Title',
            field=models.CharField(default='', max_length=225),
        ),
    ]
